#!/bin/bash

# 如果出错则中止
set -e

# 安装nix
# 如果已经有nix, 则不安装
if [ -d /nix ]; then
	# 打印nix版本
	nix --version
	echo "Nix is already installed, I will skip install"
else
	bash <(curl -L https://nixos.org/nix/install) --daemon
fi

# 修改nix的配置文件
echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf >/dev/null

# clone仓库
git clone git@github.com:kevin1sMe/dev-with-nix.git

# 进入仓库
cd dev-with-nix

# 配置userconfig.toml
cp config-tmpl.toml ${HOME}/.dev-with-nix.toml

# 提示
echo


echo -e "\xF0\x9F\x8E\x89 \e[32mNow only four simple steps:\e[0m\n"

echo -e "1. \xF0\x9F\x94\xA7 \e[32mSource the Nix profile with:\e[0m \e[33msource ~/.nix-profile/etc/profile.d/nix.sh\e[0m"

echo -e "2. \xF0\x9F\x93\x82 \e[32mEdit config at \e[0m\e[33m${HOME}/.dev-with-nix.toml\e[0m"

echo -e "3. \xF0\x9F\x9A\x80 \e[32mCd\e[0m \e[33mdev-with-nix\e[0m \e[32mand build with command:\e[0m \e[33mnix run nixpkgs#home-manager -- switch --flake .#dev --impure\e[0m\e[32m (Grab a coffee for the initial run!)\e[0m"

echo -e "4. \xF0\x9F\x8E\xAE \e[32mStart your session with:\e[0m \e[33mzsh\e[0m"
